use milkorg;
CREATE TABLE pms_department_details
(
department_id SMALLINT(5) NOT NULL,
department_name varchar(30) not null,
department_location varchar(30) not null,
department_extension smallint(3) not null,
primary key (department_id)
);
select * from pms_department_details;
CREATE TABLE MANAGER_DETAILS
(MANAGER_ID INT(10) NOT NULL, 
MANAGER_NAME VARCHAR(50) NOT NULL,
JOB VARCHAR(50) NOT NULL,
BOSS_CODE INT(10) NOT NULL,
SALARY DECIMAL(7,2) NOT NULL,
COMMISSION INT(5),
DEPARTMENT_ID INT(5),
PRIMARY KEY( MANAGER_ID));
SELECT * FROM MANAGER_DETAILS;
CREATE TABLE PMS_UNIT_DETAILS
(
UNIT_ID INT(5) NOT NULL,
UNIT_NAME VARCHAR(10) NOT NULL,
PIECE_WEIGTH VARCHAR(15) NOT NULL,
TOTAL_PIECES INT(5) NOT NULL,
UNIT_WEIGTH DECIMAL(5,2) NOT NULL,
PRIMARY KEY (UNIT_ID)
); 
SELECT * FROM PMS_UNIT_DETAILS;
CREATE TABLE PMS_PRODUCT
(
PRODUCT_ID VARCHAR(5) PRIMARY KEY,
PRODUCT_NAME VARCHAR(30) NOT NULL,
DEPARTEMENT_ID INT(10));
SELECT * FROM PMS_PRODUCT;
CREATE TABLE PMS_PRODUCT_UNIT
(
PRODUCT_ID VARCHAR(30),
UNIT_ID VARCHAR(2));
CREATE TABLE PMS_MANUFACTURING
(
MANUFACTURE_ID VARCHAR(5) PRIMARY KEY,
PRODUCT_ID VARCHAR(5) NOT NULL






